### ISSUE TITLE
Documentation on How to Deploy Pool

### ISSUE THREAD

**Issue by Fi3** [stratum-mining/sri-docs#14]

**Comment by hamzzy** [comment]
I'm interested in contributing to this, any guide on how to get started.

I'm still new to stratum for pool mining
@Fi3

**Comment by Fi3** [comment]
Hi is still a bit early for this task. If you are interested in writing documentation there are other things that can be done, if you are interested in writing some code also. We can discuss it on the Sv2 discord https://discord.com/channels/950687892169195530/950687892169195533
Or if you prefer we have an weekly call (every Thursday an 16:00 CET)

**Comment by hamzzy** [comment]
sure, I'm interested in contributing by writing some code too, also  weekly call is fine by me to catch up  every Thursday
@Fi3 
also, that discord link seems broken

here is my discord  id: hamzzy#6115

**Comment by pavlenex** [comment]
Hey @hamzzy just seen this, could you please try  joining via this link? https://discord.gg/fsEW23wFYs

**Comment by rrybarczyk** [comment]
Need to add a full explainer to official docs. I need to make a new repo for docs and move this issue there.
