### ISSUE TITLE
Documentation on How To Deploy Proxy

### ISSUE THREAD

**Issue by Fi3** [stratum-mining/sri-docs#15]

**Comment by rrybarczyk** [comment]
Need to add a full explainer to official docs. I need to make a new repo for docs and move this issue there.

**Comment by pavlenex** [comment]
We have everything here now https://github.com/stratum-mining/stratum/tree/main/roles/translator#sv1-to-sv2-translator-proxy I'll transfer this issue to docs repo so we can make it more prominent once we have our docs.
